services:
  surefinsync:
    build: .
    container_name: surefinsync
    env_file:
      - .env
    volumes:
      - ./:/app
      - ${TRANSACTIONS_DIR}:/app/transactions
      - ${MERGED_TRANSACTIONS_DIR}:/app/merged
    tty: true